service: sl-http

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs4.3

functions:
  post-question:
    handler: handler.endpoint
    events:
      - http:
          path: q/{qid}
          method: post


