service: sl-http

frameworkVersion: ">=1.1.0 <2.0.0"


provider:
  name: aws
  runtime: nodejs6.10
  role: arn:aws:iam::031998557027:role/admin_lambda

functions:
  post-question:
    handler: handler.endpoint
    events:
      - http:
          path: q/{qid}
          method: get


